version: "3.9"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      JWT_SECRET: "dev-secret-change-me"
      JWT_TTL_SECONDS: "3600"
      # DB connection info for the app to connect to postgres
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: template
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge
